// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhlqyubupijgccfrhsay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJobHF5dWJ1cGlqZ2NjZnJoc2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mjk0NDIsImV4cCI6MjA3MzAwNTQ0Mn0.y9-z5G2l1EtqHfknQioiw5w0azcq3YV1oav3SwD83zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});